name: Auto Update Hosts

on:
  schedule:
    - cron: '0 20 * * *'
  workflow_dispatch:

jobs:
  update-and-push:
    runs-on: ubuntu-latest
    
    # 显式告诉 Runner 使用 Node 24 来运行所有的 JS Actions
    env:
      FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

    permissions:
      contents: write

    steps:
      - name: Checkout Repository
        # 建议检查并使用最新的稳定版本
        uses: actions/checkout@v4

      - name: Fetch, Merge, and Clean Hosts
        run: |
          echo "开始下载并处理 hosts 数据源..."
          # URL1="https://raw.githubusercontent.com/Mice-Tailor-Infra/fcm-hosts-next/refs/heads/main/fcm_dual.hosts"
          URL1="https://raw.githubusercontent.com/yanpuzhen/fcm-hosts/refs/heads/main/hosts.txt"
         
         
          # 下载、去注释、去空行
          curl -sL "$URL1" | sed 's/#.*//' | awk 'NF' > hosts.txt
          
          echo "处理完成！记录总数："
          wc -l hosts.txt

      - name: Commit and Push Changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          
          if [ -n "$(git status --porcelain)" ]; then
            git add hosts.txt
            git commit -m "Auto-update hosts.txt $(date +'%Y-%m-%d %H:%M:%S')"
            git push
          else
            echo "无变化，跳过。"
          fi
